# Generated by Django 5.0.7 on 2025-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.PositiveIntegerField(unique=True)),
                ('student_class', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('created_At', models.DateTimeField(auto_now_add=True)),
                ('updated_At', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['roll'],
            },
        ),
    ]
